#!/usr/bin/env python3
"""Extract printable-ASCII outlines from a monospace font into vendor/mono-glyphs.js.

The card generator renders share text as vector paths, so a laser never has to
resolve a font. Paths are in font units with the origin on the baseline and y
pointing up; the SVG renderer flips and scales them.
"""

import json
import sys
from pathlib import Path

from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.ttLib import TTFont

FONT = Path("/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf")
OUT = Path(__file__).resolve().parent.parent / "vendor" / "mono-glyphs.js"


def main() -> int:
    font = TTFont(FONT)
    cmap = font.getBestCmap()
    glyphs = font.getGlyphSet()
    metrics = font["hmtx"]

    out = {}
    advances = set()
    for cp in range(0x20, 0x7F):
        name = cmap.get(cp)
        if name is None:
            continue
        pen = SVGPathPen(glyphs)
        glyphs[name].draw(pen)
        out[chr(cp)] = pen.getCommands()
        advances.add(metrics[name][0])

    if len(advances) != 1:
        print(f"font is not monospace: advances {sorted(advances)}", file=sys.stderr)
        return 1

    payload = {
        "unitsPerEm": font["head"].unitsPerEm,
        "advance": advances.pop(),
        "glyphs": out,
    }
    OUT.write_text(
        "// Generated by tools/build-glyphs.py from DejaVu Sans Mono. Do not edit.\n"
        "var MONO_GLYPHS = " + json.dumps(payload, separators=(",", ":")) + ";\n"
    )
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes, {len(out)} glyphs)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
